<?php

/**
 * Implements hook_menu().
 */
function cle_dashboard_menu() {
  $items['cle-dashboard'] = array(
    'title' => 'CLE Dashboard',
    'page callback' => 'cle_dashboard_page',
    'access arguments' => array('access cle dashboard'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cle_dashboard_permission() {
  return array(
    'access cle dashboard' =>  array(
      'title' => t('Administer CLE dashboard'),
      'description' => t('Ability to access CLE managment dashboard.'),
    ),
  );
}

function cle_dashboard_page() {
  return theme('cle_dashboard');
}

/**
 * Implements hook_theme().
 */
function cle_dashboard_theme($existing, $type, $theme, $path) {
  return array(
    'cle_dashboard' => array(
      'variables' => array('content' => NULL),
      'template' => 'templates/cle-dashboard',
    ),
  );
}

/**
 * Implementation of hook_preprocess_cle_controlboard().
 */
function cle_dashboard_preprocess_cle_dashboard(&$variables) {
  drupal_add_css('https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css', array('type' => 'external'));
  drupal_add_css('https://fonts.googleapis.com/icon?family=Material+Icons', array('type' => 'external'));
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.js', array('type' => 'external'));
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-sanitize.js', array('type' => 'external'));
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js', array('type' => 'external'));
  drupal_add_css(drupal_get_path('module', 'cle_dashboard') . '/css/cle-dashboard.css');
  drupal_add_js(drupal_get_path('module', 'cle_dashboard') . '/js/app.js');

  // Instantiate the user
  global $user;
   
  $assignments = array();
  $assignments_ids = array();
  $my_submissions = array();
  $my_critiques = array();

  // Get a list of assignments
  $view_results = views_get_view_result('cle_dashboard'); 
  if ($view_results) {
    // ALWAYS REMOVE THE FIELD DATA TO PREVENT DATA FROM LEAKING OUT!!!
    foreach ($view_results as $key => $result) {
      unset($view_results[$key]->_field_data);
      $assignments_ids[] = $result->nid;
      $assignments[$result->nid] = $result;
    }
  }

  // Get a list of 'My Submissions'
  $view_results = views_get_view_result('cle_dashboard_my_submissions', 'Master', $user->uid); 
  if ($view_results) {
    // ALWAYS REMOVE THE FIELD DATA TO PREVENT DATA FROM LEAKING OUT!!!
    foreach ($view_results as $key => $result) {
      unset($view_results[$key]->_field_data);
      $my_submissions = $view_results;
    }
  }

  // Get a list of 'My Critiques'
  $view_results = views_get_view_result('cle_dashboard_my_critiques', 'Master', $user->uid); 
  if ($view_results) {
    // ALWAYS REMOVE THE FIELD DATA TO PREVENT DATA FROM LEAKING OUT!!!
    foreach ($view_results as $key => $result) {
      unset($view_results[$key]->_field_data);
      $my_critiques = $view_results;
    }
  }

  drupal_add_js(array('cleDashboard' => array('assignments' => $assignments, 'submissions' => $my_submissions, 'critiques' => $my_critiques)), 'setting');
}

